unvanquished: 0.9.0-1~getdeb1
  * New upstream version

diff --git a/unvanquished/scripts/unvanquished b/unvanquished/scripts/unvanquished
--- a/unvanquished/scripts/unvanquished
+++ b/unvanquished/scripts/unvanquished
@@ -1,6 +1,36 @@
-#! /bin/sh
-
-sed -i -e 's/^bind \\/bind BACKSLASH/' ~/.Unvanquished/*/*.cfg
-
+#!/bin/sh
 cd /usr/lib/games/unvanquished
-exec ./unvanquished +set fs_libpath "$PWD" +set fs_basepath /usr/share/games/unvanquished +reset protocol "$@"
+unvanquished-migrate-profile
+
+# Assumptions:
+# - if there's a URI, it's the first parameter
+# - pipe file presence == Unvanquished is running
+# - the pipe file's name hasn't been changed
+
+echo "$1" | LANG=C grep -q '^unv://\(\[[0-9A-Fa-f:]\+\]\|[-.A-Za-z0-9]\+\)\(:[0-9]\+\)\?/\?$'
+NOT_URI=$?
+
+if test -p ~/.Unvanquished/main/pipe; then
+  if test $NOT_URI != 0; then
+    echo "$0: invalid URI: $1" >&2
+    exit 2
+  fi
+  # Just pass on the URI; drop the rest
+  echo "connect $1" >~/.Unvanquished/main/pipe
+  exit
+fi
+
+PRECMD=
+if test $NOT_URI = 0; then
+  PRECMD='connect '
+else
+  echo "$1" | LANG=C grep -qi '^unv://'
+  if test $? = 0; then
+    echo "$0: invalid URI: $1" >&2
+    exit 2
+  fi
+fi
+
+exec ./unvanquished +set fs_libpath "$PWD" +set fs_basepath /usr/share/games/unvanquished +$PRECMD"$@"
+
+rm -f ~/.Unvanquished/main/pipe
